mock = True
schedule_sleep_time_in_seconds = 3
headless = False
max_workers = 8
max_workers_for_sms = 4
sms_activate_key = "c73409c5c0Ab927ded2d1cc313d03be9"
unique_numbers = True
time_to_retry_in_hours_when_proxy_is_blocked = 1
use_proxy = False
do_nothing_before_action = False
default_timeout = 180000
auth_enabled = True
tasks_enabled = True
static_dir_path = "/home/nikolay/Documents/static/"
# db_path = "/opt/wb.db"
