mock = False
schedule_sleep_time_in_seconds = 5
headless = False
max_workers = 10
max_workers_for_sms = 1
sms_activate_key = "44009Adc5f856793db4A6bAe6d7e37bd"
unique_numbers = True
time_to_retry_in_hours_when_proxy_is_blocked = 1
use_proxy = True
# db_path = "/opt/wb.db"
